import '../styles/globals.css'
import Layout from "../components/Layout";
import {ApolloProvider,} from "@apollo/client";
import {apolloClient} from "../apolloClient";
import Head from "next/head";
// 1. Import `extendTheme`
import {ChakraProvider, extendTheme} from '@chakra-ui/react'

// 2. Call `extendTheme` and pass your custom values
const theme = extendTheme({
    colors: {
        gold: {
            '50':  '#fbfaf4',
            '100': '#f8efc4',
            '200': '#f0db8e',
            '300': '#dab65b',
            '400': '#be8c34',
            '500': '#a06d1c',
            '600': '#835312',
            '700': '#653f10',
            '800': '#452b0e',
            '900': '#2e1b0a',
        },
        olive: {
            '50':  '#f9f9f3',
            '100': '#f4efcf',
            '200': '#e6de9e',
            '300': '#c6bc69',
            '400': '#98953e',
            '500': '#777722',
            '600': '#605e17',
            '700': '#4b4714',
            '800': '#333111',
            '900': '#231f0d',
        },
        green: {
            '50':  '#f4f7f5',
            '100': '#e4efeb',
            '200': '#c4e2d4',
            '300': '#91c4aa',
            '400': '#51a17e',
            '500': '#3b8457',
            '600': '#316c41',
            '700': '#2a5234',
            '800': '#1e3827',
            '900': '#14231c',
        },
        teal: {
            '50':  '#f1f6f6',
            '100': '#d9eff4',
            '200': '#aee2e6',
            '300': '#77c6c9',
            '400': '#3ba5a5',
            '500': '#2b8882',
            '600': '#256f68',
            '700': '#215552',
            '800': '#183a3c',
            '900': '#10252a',
        },
        navy: {
            '50':  '#f4f7f7',
            '100': '#deeff7',
            '200': '#b9dfee',
            '300': '#87c1d7',
            '400': '#509dbb',
            '500': '#3c7ea0',
            '600': '#326486',
            '700': '#2a4b68',
            '800': '#1e344b',
            '900': '#132132',
        },
        cyan: {
            '50':  '#f5f8f9',
            '100': '#e4eff9',
            '200': '#c5dcf2',
            '300': '#99bbe1',
            '400': '#6a95cc',
            '500': '#5374b7',
            '600': '#45599f',
            '700': '#37437d',
            '800': '#262e59',
            '900': '#171d39',
        },
        indigo: {
            '50':  '#f8f9fa',
            '100': '#eceff8',
            '200': '#d8d8f2',
            '300': '#b6b3e1',
            '400': '#958bcc',
            '500': '#7b68b8',
            '600': '#654d9f',
            '700': '#4d3a7c',
            '800': '#352856',
            '900': '#201a34',
        },
        beaver: {
            '50':  '#fbfaf9',
            '100': '#f7efed',
            '200': '#eed5db',
            '300': '#daadb7',
            '400': '#ca818f',
            '500': '#b35f6e',
            '600': '#974451',
            '700': '#73333d',
            '800': '#50232a',
            '900': '#311719',
        },
        ochre: {
            '50':  '#fbfaf7',
            '100': '#f9efdc',
            '200': '#f2d7b9',
            '300': '#dfaf88',
            '400': '#cd845a',
            '500': '#b56239',
            '600': '#984827',
            '700': '#75361f',
            '800': '#512617',
            '900': '#34180f',
        },
    }
})

function MyApp({Component, pageProps}) {
    return (
        <ApolloProvider client={apolloClient}>
            <Head>
                <title>History DB</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <ChakraProvider theme={theme}>
                <Layout>
                    <Component {...pageProps} />
                </Layout>
            </ChakraProvider>
        </ApolloProvider>
    )
}

export default MyApp
