import '../styles/globals.css'
import Layout from "../components/Layout";
import {ApolloProvider,} from "@apollo/client";
import {apolloClient} from "../apolloClient";
import Head from "next/head";
import { ChakraProvider } from '@chakra-ui/react'

function MyApp({Component, pageProps}) {
    return (
        <ApolloProvider client={apolloClient}>
            <Head>
                <title>History DB</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <ChakraProvider>
                <Layout>
                    <Component {...pageProps} />
                </Layout>
            </ChakraProvider>
        </ApolloProvider>
    )
}

export default MyApp
