import '../styles/globals.css'
import Layout from "../components/layout";
import {
    ApolloClient,
    InMemoryCache,
    ApolloProvider,
} from "@apollo/client";
import {apolloClient} from "../apolloClient";
import Head from "next/head";

function MyApp({Component, pageProps}) {
    return (
        <ApolloProvider client={apolloClient}>
            <Head>
                <title>History DB</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Layout>
                <Component {...pageProps} />
            </Layout>
        </ApolloProvider>
    )
}

export default MyApp
