import Head from 'next/head'
import Header from "../components/header";

export default function Home() {
    return (<div>
        <Head>
            <title>History DB</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>

        <main className="min-h-screen flex flex-col items-center justify-center bg-gray-100">
            <Header />
        </main>
    </div>);
}
